image:
  repository: harbor.vnerd.com/library/hydra
  pullPolicy: Always
  tag: latest

deployment:
  apiVersion: "apps/v1"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate

replicas: 4

#Adding velero backup for k8s services
#velero.io/exclude-from-backup" = true 
service:
  type: ClusterIP
  port: 8080
  annotations: {}
  labels: {}

# ingress:
#   enabled: true
#   ingressClassName: alb
#   labels: {}
#   hosts:
#     - dvs.eplur-staging.vnerd.com
#     - dvs-staging.vnerd.com
#   tls:
#     - hosts:
#         - dvs.eplur-staging.vnerd.com
#   path: /


resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 2
    memory: 1Gi

tolerations: []

nodeSelector: {}

config:
  LOG_DIR: /var/log/hydra/
  LOG_LEVEL: DEBUG
  HYDRA_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: b-1.isdvsdevblueuswest2.8xkirx.c14.kafka.us-west-2.amazonaws.com:9098,b-3.isdvsdevblueuswest2.8xkirx.c14.kafka.us-west-2.amazonaws.com:9098,b-2.isdvsdevblueuswest2.8xkirx.c14.kafka.us-west-2.amazonaws.com:9098
  HYDRA_SCHEMA_REGISTRY_URL: https://dvs-dev-schema-registry.eplur-staging.vnerd.com:8081
  HYDRA_V2_METADATA_CONTACT: '#dev-data-platform'
  HYDRA_REPLICATION_FACTOR: 1
  HYDRA_V2_METADATA_CONSUMER_GROUP: 'v2MetadataConsumer'
  HYDRA_V2_CREATE_TOPICS_ENABLED: 'true'
  HYDRA_V2_METADATA_CREATE_ON_STARTUP: 'true'
  HYDRA_MIN_INSYNC_REPLICAS: 1


